x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./data:/app/data

services:
  nanocat:
    container_name: nanocat
    <<: *common-config
    command: ["-w", "/app/data"]
    environment:
      NANOCAT_WEB_HOST: 0.0.0.0
      NANOCAT_WEB_PORT: 18790
    restart: unless-stopped
    ports:
      - 127.0.0.1:18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
