"""Stable contracts shared by NanoCat runtime and application layers."""

from nanocat.core.intervention import (
    DeliveryResult,
    InterventionAction,
    InterventionFlow,
    InterventionKind,
    InterventionRequest,
    InterventionResult,
    InterventionState,
    ResumeMode,
)
from nanocat.core.messages import (
    ConversationRef,
    EventEnvelope,
    InboundEvent,
    OutboundEvent,
    Principal,
    TurnRef,
)
from nanocat.core.ports import ChannelCapabilities, resolve_channel_capabilities
from nanocat.core.resources import (
    BatchFailurePolicy,
    Deadline,
    OperationBudget,
    PriorityClass,
    ResourceDescriptor,
    ResourceKind,
    ResourcePolicy,
    ResourceQuota,
    ResourceSnapshot,
)
from nanocat.core.runtime import (
    CancellationRequestedError,
    CancellationToken,
    CapabilityDescriptor,
    ErrorCategory,
    HealthState,
    RuntimeComponent,
    ShutdownReason,
)

__all__ = [
    "CancellationRequestedError",
    "CancellationToken",
    "ChannelCapabilities",
    "resolve_channel_capabilities",
    "BatchFailurePolicy",
    "CapabilityDescriptor",
    "ConversationRef",
    "DeliveryResult",
    "ErrorCategory",
    "EventEnvelope",
    "HealthState",
    "InboundEvent",
    "InterventionAction",
    "InterventionFlow",
    "InterventionKind",
    "InterventionRequest",
    "InterventionResult",
    "InterventionState",
    "Deadline",
    "OperationBudget",
    "OutboundEvent",
    "PriorityClass",
    "Principal",
    "ResourceDescriptor",
    "ResourceKind",
    "ResourcePolicy",
    "ResourceQuota",
    "ResourceSnapshot",
    "ResumeMode",
    "RuntimeComponent",
    "ShutdownReason",
    "TurnRef",
]
